config/routes.rb
Rails.application.routes.draw do
  root :to => 'top#index'
  resources :bus_stops
  resources :specifics
  resources :chats
  resources :shops
  resources :clubs
  resources :clubs
  resources :clubs
  resources :goods
  resources :groups
  resources :locations
  resources :projects

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  has_many :bus_timetables, ->{order(:depart_time)}
  accepts_nested_attributes_for :bus_timetables, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/bus_timetable.rb
class BusTimetable < ActiveRecord::Base
  belongs_to :bus_stop
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :group
  belongs_to :location
end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :good
  belongs_to :shop
end

app/models/good.rb
class Good < ActiveRecord::Base
  has_many :good_anothers
  accepts_nested_attributes_for :good_anothers, allow_destroy: true, reject_if: :all_blank
  has_many :exhibits
  has_many :shops, :through => :exhibits

  validates :name, presence: true
end

app/models/good_another.rb
class GoodAnother < ActiveRecord::Base
  belongs_to :good
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :clubs
  has_many :group_anothers
  has_many :shops
  accepts_nested_attributes_for :group_anothers, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/group_another.rb
class GroupAnother < ActiveRecord::Base
  belongs_to :group
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :projects
  has_many :clubs
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :location
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :group
  has_many :exhibits
  has_many :goods, :through => :exhibits
  accepts_nested_attributes_for :exhibits, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/specific.rb
class Specific < ActiveRecord::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:start_time, :end_time, :name, :group_id, :location_id, :introduction, :keyword)
    end

end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <label>開催期間</label>
    <div class="form-inline form-group">
      <div class ='input-group date datepicker'>
        <%= f.text_field :start_time, :class => 'form-control' %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
      <span>〜</span>
      <div class ='input-group date datepicker'>
        <%= f.text_field :end_time, :class => 'form-control' %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :name, 'サークル展名' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :group_id, '展示団体' %><br>
    <%= f.collection_select :group_id, Group.all, :id, :name %>
  </div>
  <div class="field form-group">
    <%= f.label :location_id, '展示場所' %><br>
    <%= f.collection_select :location_id, Location.all, :id, :name %>
  </div>
  <div class="field form-group">
    <%= f.label :introduction, '説明文' %><br>
    <%= f.text_area :introduction %>
  </div>
  <div class="field form-group">
    <%= f.label :keyword, '反応語句(改行区切り)' %><br>
    <%= f.text_area :keyword %>
  </div>
  <div class="actions">
    <%= f.submit "更新・登録", :class => "btn btn-default"%>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>サークル展示編集</h1>

<%= render 'form' %>

<%= link_to '詳細に戻る', @club , :class => "btn btn-primary"%>
<%= link_to '一覧に戻る', clubs_path, :class => "btn btn-default" %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>サークル展示一覧</h1>

<%= link_to "トップ", root_path, :class => "btn btn-success pull-right" %>
<%= link_to "団体登録", groups_path, :class => "btn btn-success pull-right" %>
<%= link_to "場所登録", locations_path, :class => "btn btn-success pull-right" %>

<%= link_to '新しいサークル展示を登録', new_club_path, :class => "btn btn-success" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>開催期間</th>
      <th>サークル展名</th>
      <th>展示団体</th>
      <th>展示場所</th>
      <th>説明文</th>
      <th>反応語句</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.start_time.to_s(:view) %><br>~<br><%= club.end_time.to_s(:view) %></td>
        <td><%= club.name %></td>
        <td><%= club.group.name %></td>
        <td><%= club.location.name %></td>
        <td><%= simple_format(club.introduction) %></td>
        <td><%= simple_format(club.keyword) %></td>
        <td><%= link_to '詳細', club, :class => "btn btn-primary btn-sm" %></td>
        <td><%= link_to '編集', edit_club_path(club), :class => "btn btn-success btn-sm" %></td>
        <td><%= link_to '削除', club, :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: '本当にこのサークル展示を削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clubs/new.html.erb
<h1>サークル展示登録</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', clubs_path, :class => "btn btn-default" %>

app/views/clubs/show.html.erb
<p>
  <strong>開催期間:</strong>
  <%= @club.start_time.to_s(:view) %>~<%= @club.end_time.to_s(:view) %>
</p>

<p>
  <strong>サークル展名:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>展示団体:</strong>
  <%= @club.group.name %>
</p>

<p>
  <strong>展示場所:</strong>
  <%= @club.location.name %>
</p>

<p>
  <strong>説明文:</strong>
  <%= simple_format(@club.introduction) %>
</p>

<p>
  <strong>反応語句:</strong>
  <%= simple_format(@club.keyword) %>
</p>

<%= link_to '編集', edit_club_path(@club), :class => "btn btn-success" %>
<%= link_to '一覧に戻る', clubs_path, :class => "btn btn-default" %>