config/routes.rb
Rails.application.routes.draw do
  root :to => 'top#index'
  resources :bus_stops
  resources :specifics
  resources :chats
  resources :shops
  resources :clubs
  resources :clubs
  resources :clubs
  resources :goods
  resources :groups
  resources :locations
  resources :projects

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  has_many :bus_timetables, ->{order(:depart_time)}
  accepts_nested_attributes_for :bus_timetables, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/bus_timetable.rb
class BusTimetable < ActiveRecord::Base
  belongs_to :bus_stop
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :group
  belongs_to :location
end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :good
  belongs_to :shop
end

app/models/good.rb
class Good < ActiveRecord::Base
  has_many :good_anothers
  accepts_nested_attributes_for :good_anothers, allow_destroy: true, reject_if: :all_blank
  has_many :exhibits
  has_many :shops, :through => :exhibits

  validates :name, presence: true
end

app/models/good_another.rb
class GoodAnother < ActiveRecord::Base
  belongs_to :good
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :clubs
  has_many :group_anothers
  has_many :shops
  accepts_nested_attributes_for :group_anothers, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/group_another.rb
class GroupAnother < ActiveRecord::Base
  belongs_to :group
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :projects
  has_many :clubs
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :location
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :group
  has_many :exhibits
  has_many :goods, :through => :exhibits
  accepts_nested_attributes_for :exhibits, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/specific.rb
class Specific < ActiveRecord::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    @shop.exhibits.build
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(
        :name, :group_id, :booth,
        exhibits_attributes: [:id, :good_id, :shop_id, :_destroy]
      )
    end
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/shops/_exhibit_fields.html.erb
<fieldset>
  <%= f.label :name, '出品物' %>
  <%= f.collection_select :good_id, Good.all, :id, :name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "削除", '#', class: "remove_fields btn btn-danger" %>
</fieldset>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '模擬店名' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_id, '出店団体' %><br>
    <%= f.collection_select :group_id, Group.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :booth, '出店場所' %><br>
    <%= f.number_field :booth %>
  </div>
  <div class="field">
    <%= f.label :exhibits, '出品物一覧' %>
    <%= f.fields_for :exhibits do |builder| %>
      <%= render "exhibit_fields", f: builder %>
    <% end %>
    <%= link_to_add_fields "追加", f, :exhibits %>
  </div>
  <div class="actions">
    <%= f.submit "更新・登録", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>模擬店編集</h1>

<%= render 'form' %>

<%= link_to '詳細に戻る', @shop, :class => "btn btn-primary" %>
<%= link_to '一覧に戻る', shops_path, :class => "btn btn-default" %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>模擬店一覧</h1>

<%= link_to "トップ", root_path, :class => "btn btn-success pull-right" %>
<%= link_to "出店物登録", goods_path, :class => "btn btn-success pull-right" %>
<%= link_to "団体登録", groups_path, :class => "btn btn-success pull-right" %>

<%= link_to '新しい模擬店を登録', new_shop_path, :class => "btn btn-success" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>模擬店名</th>
      <th>出店団体</th>
      <th>出店場所</th>
      <th>出品物</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.group.name %></td>
        <td><%= shop.booth %></td>
        <td>
          <% shop.goods.each do |good| %>
            <%= good.name %><br>
          <% end %>
        </td>
        <td><%= link_to '詳細', shop, :class => "btn btn-primary btn-sm" %></td>
        <td><%= link_to '編集', edit_shop_path(shop), :class => "btn btn-success btn-sm" %></td>
        <td><%= link_to '削除', shop, :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: '本当にこの模擬店を削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shops/new.html.erb
<h1>新しい模擬店を登録</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', shops_path, :class => "btn btn-default" %>

app/views/shops/show.html.erb
<p>
  <strong>模擬店名:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>出店団体:</strong>
  <%= @shop.group.name %>
</p>

<p>
  <strong>出店場所:</strong>
  <%= @shop.booth %>
</p>

<p>
  <strong>出品物:</strong><br>
  <% @shop.goods.each do |good| %>
  <%= good.name %><br>
  <% end %>
</p>

<%= link_to '編集', edit_shop_path(@shop), :class => "btn btn-success" %>
<%= link_to '一覧に戻る', shops_path, :class => "btn btn-default" %>