config/routes.rb
Rails.application.routes.draw do
  root :to => 'top#index'
  resources :bus_stops
  resources :specifics
  resources :chats
  resources :shops
  resources :clubs
  resources :clubs
  resources :clubs
  resources :goods
  resources :groups
  resources :locations
  resources :projects

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  has_many :bus_timetables, ->{order(:depart_time)}
  accepts_nested_attributes_for :bus_timetables, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/bus_timetable.rb
class BusTimetable < ActiveRecord::Base
  belongs_to :bus_stop
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :group
  belongs_to :location
end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :good
  belongs_to :shop
end

app/models/good.rb
class Good < ActiveRecord::Base
  has_many :good_anothers
  accepts_nested_attributes_for :good_anothers, allow_destroy: true, reject_if: :all_blank
  has_many :exhibits
  has_many :shops, :through => :exhibits

  validates :name, presence: true
end

app/models/good_another.rb
class GoodAnother < ActiveRecord::Base
  belongs_to :good
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :clubs
  has_many :group_anothers
  has_many :shops
  accepts_nested_attributes_for :group_anothers, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/group_another.rb
class GroupAnother < ActiveRecord::Base
  belongs_to :group
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :projects
  has_many :clubs
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :location
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :group
  has_many :exhibits
  has_many :goods, :through => :exhibits
  accepts_nested_attributes_for :exhibits, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/specific.rb
class Specific < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.group_anothers.build
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(
        :name,
        group_anothers_attributes: [:id, :name, :_destroy]
      )
    end
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '団体名' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_anothers, '別名登録' %><br>
    <%= f.fields_for :group_anothers do |builder| %>
      <%= render "group_another_fields", f: builder %>
    <% end %>
    <%= link_to_add_fields "追加", f, :group_anothers %>
  </div>
  <div class="actions">
    <%= f.submit "更新・登録", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/groups/_group_another_fields.html.erb
<fieldset>
  <%= f.label :name, '別名:' %>
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "削除", '#', class: "remove_fields btn btn-danger" %><br>
</fieldset>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to '詳細に戻る', @group, :class => "btn btn-primary" %>
<%= link_to '一覧に戻る', groups_path , :class => "btn btn-default" %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>団体一覧</h1>

<%= link_to "トップ", root_path, :class => "btn btn-success pull-right" %>
<%= link_to "模擬店登録", shops_path, :class => "btn btn-success pull-right" %>
<%= link_to "サ展登録", clubs_path, :class => "btn btn-success pull-right" %>

<%= link_to '新しい団体を登録する', new_group_path, :class => "btn btn-success" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>団体名</th>
      <th>別名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td>
          <% group.group_anothers.each do |another| %>
            <%= another.name %><br>
          <% end %>
        </td>
        <td><%= link_to '詳細', group, :class => "btn btn-primary btn-sm" %></td>
        <td><%= link_to '編集', edit_group_path(group), :class => "btn btn-success btn-sm" %></td>
        <td><%= link_to '削除', group, :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: '本当にこの団体を削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/groups/new.html.erb
<h1>団体登録</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', groups_path, :class => "btn btn-default" %>

app/views/groups/show.html.erb
<p>
  <strong>団体名:</strong>
  <%= @group.name %><br>
</p>

<p>
  <strong>別名:</strong><br>
  <% @group.group_anothers.each do |another| %>
    <%= another.name %><br>
  <% end %>
</p>

<%= link_to '編集', edit_group_path(@group), :class => "btn btn-success" %>
<%= link_to '一覧に戻る', groups_path, :class => "btn btn-default" %>