config/routes.rb
Rails.application.routes.draw do
  root :to => 'top#index'
  resources :bus_stops
  resources :specifics
  resources :chats
  resources :shops
  resources :clubs
  resources :clubs
  resources :clubs
  resources :goods
  resources :groups
  resources :locations
  resources :projects

end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  has_many :bus_timetables, ->{order(:depart_time)}
  accepts_nested_attributes_for :bus_timetables, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/bus_timetable.rb
class BusTimetable < ActiveRecord::Base
  belongs_to :bus_stop
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :group
  belongs_to :location
end

app/models/exhibit.rb
class Exhibit < ActiveRecord::Base
  belongs_to :good
  belongs_to :shop
end

app/models/good.rb
class Good < ActiveRecord::Base
  has_many :good_anothers
  accepts_nested_attributes_for :good_anothers, allow_destroy: true, reject_if: :all_blank
  has_many :exhibits
  has_many :shops, :through => :exhibits

  validates :name, presence: true
end

app/models/good_another.rb
class GoodAnother < ActiveRecord::Base
  belongs_to :good
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :clubs
  has_many :group_anothers
  has_many :shops
  accepts_nested_attributes_for :group_anothers, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/group_another.rb
class GroupAnother < ActiveRecord::Base
  belongs_to :group
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :projects
  has_many :clubs
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :location
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :group
  has_many :exhibits
  has_many :goods, :through => :exhibits
  accepts_nested_attributes_for :exhibits, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
end

app/models/specific.rb
class Specific < ActiveRecord::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name)
    end
end

app/helpers/bus_stops_helper.rb
module BusStopsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '場所名' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "更新・登録", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>場所編集</h1>

<%= render 'form' %>

<%= link_to '詳細に戻る', @location, :class => "btn btn-primary" %> 
<%= link_to '一覧に戻る', locations_path, :class => "btn btn-default" %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>場所一覧</h1>

<%= link_to "トップ", root_path, :class => "btn btn-success pull-right" %>
<%= link_to "企画登録", projects_path, :class => "btn btn-success pull-right" %>
<%= link_to "サ展登録", clubs_path, :class => "btn btn-success pull-right" %>

<%= link_to '新しい場所を登録する', new_location_path, :class => "btn btn-success" %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>場所名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= link_to '詳細', location, :class => "btn btn-primary btn-sm" %></td>
        <td><%= link_to '編集', edit_location_path(location), :class => "btn-success btn-sm" %></td>
        <td><%= link_to '削除', location, :class => "btn btn-danger btn-sm", method: :delete, data: { confirm: '本当にこの場所を削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/locations/new.html.erb
<h1>場所登録</h1>

<%= render 'form' %>

<%= link_to '一覧に戻る', locations_path, :class => "btn btn-default" %>

app/views/locations/show.html.erb
<p>
  <strong>場所名:</strong>
  <%= @location.name %>
</p>

<%= link_to '編集', edit_location_path(@location), :class => "btn btn-success" %> 
<%= link_to '一覧に戻る', locations_path, :class => "btn btn-default" %>